/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Samsung
 */
public class GraveRunOTP extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraveRunOTP.class.getName());

    /**
     * Creates new form GraveRunOTP
     */
    public GraveRunOTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GraveRunOTP = new javax.swing.JPanel();
        GRAVERUN = new javax.swing.JLabel();
        logan = new javax.swing.JLabel();
        ForgetYourPassword = new javax.swing.JLabel();
        enteremail = new javax.swing.JLabel();
        changepassword = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GraveRunOTP.setBackground(new java.awt.Color(0, 0, 0));

        GRAVERUN.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        GRAVERUN.setForeground(new java.awt.Color(204, 204, 204));
        GRAVERUN.setText("  GRAVERUN");
        GRAVERUN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 0)));

        logan.setForeground(new java.awt.Color(255, 255, 255));
        logan.setText("RUN BEYOND THE GRAVE");

        ForgetYourPassword.setBackground(new java.awt.Color(0, 0, 0));
        ForgetYourPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ForgetYourPassword.setForeground(new java.awt.Color(204, 204, 204));
        ForgetYourPassword.setText("       Forget Your Password?");

        enteremail.setBackground(new java.awt.Color(0, 0, 0));
        enteremail.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        enteremail.setForeground(new java.awt.Color(204, 204, 204));
        enteremail.setText("Enter the OTP sent to your E-mail to reset your password.");

        changepassword.setBackground(new java.awt.Color(204, 0, 0));
        changepassword.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        changepassword.setForeground(new java.awt.Color(255, 255, 255));
        changepassword.setLabel("Change Password");

        javax.swing.GroupLayout GraveRunOTPLayout = new javax.swing.GroupLayout(GraveRunOTP);
        GraveRunOTP.setLayout(GraveRunOTPLayout);
        GraveRunOTPLayout.setHorizontalGroup(
            GraveRunOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraveRunOTPLayout.createSequentialGroup()
                .addGroup(GraveRunOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GraveRunOTPLayout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(GRAVERUN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GraveRunOTPLayout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(logan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GraveRunOTPLayout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addComponent(ForgetYourPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GraveRunOTPLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(enteremail, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GraveRunOTPLayout.createSequentialGroup()
                        .addGap(527, 527, 527)
                        .addComponent(changepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        GraveRunOTPLayout.setVerticalGroup(
            GraveRunOTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraveRunOTPLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(GRAVERUN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(ForgetYourPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enteremail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(changepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        changepassword.getAccessibleContext().setAccessibleName(" Change Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GraveRunOTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GraveRunOTP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GraveRunOTP().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ForgetYourPassword;
    private javax.swing.JLabel GRAVERUN;
    private javax.swing.JPanel GraveRunOTP;
    private java.awt.Button changepassword;
    private javax.swing.JLabel enteremail;
    private javax.swing.JLabel logan;
    // End of variables declaration//GEN-END:variables
}
